change multiprocess test start from Process to Map to capture exceptions from child processes (#3614)
Summary:

# context
* in `MultiProcessTestBase` the multi-rank environment is generated by multiprocessing.Process, which can't propagate the error message from child process to the main process (which outputs the error log)
* this makes the exception in child process hidden in the github workflow failure
* change the mutiprocess start method to multiprocessing.Pool.map

NOTE: this change requires all the `caller` function has `rank` as the first argument.

# result
* before
```
======================================================================
FAIL: test_sharding_cw (torchrec.distributed.tests.test_model_parallel_nccl.ModelParallelTestNccl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/test_model_parallel.py", line 434, in test_sharding_cw
    sharder_type=st.sampled_from(
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/hypothesis/core.py", line 1602, in wrapped_test
    raise the_error_hypothesis_found
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/test_model_parallel.py", line 491, in test_sharding_cw
    self._test_sharding(
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/test_model_parallel.py", line 198, in _test_sharding
    self._run_multi_process_test(
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/multi_process.py", line 161, in _run_multi_process_test
    self.assertEqual(0, p.exitcode)
AssertionError: 0 != 1
Falsifying example: test_sharding_cw(
    self=<torchrec.distributed.tests.test_model_parallel_nccl.ModelParallelTestNccl testMethod=test_sharding_cw>,
    sharder_type='embedding_bag_collection',
    kernel_type='fused',  # or any other generated value
    qcomms_config=None,  # or any other generated value
    apply_optimizer_in_backward_config=None,  # or any other generated value
    variable_batch_size=False,  # or any other generated value
    data_type=DataType.FP32,  # or any other generated value
    allow_zero_batch_size=False,  # or any other generated value
)

----------------------------------------------------------------------
Ran 1 test in 331.866s

FAILED (failures=1)
```

* after
```
======================================================================
ERROR: test_sharding_cw (torchrec.distributed.tests.test_model_parallel_nccl.ModelParallelTestNccl)
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/fbcode/platform010/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/fbcode/platform010/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/test_sharding.py", line 1080, in sharding_single_rank_test
    sharding_single_rank_test_single_process(
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/test_sharding.py", line 796, in sharding_single_rank_test_single_process
    raise RuntimeError("injected error for testing")
RuntimeError: injected error for testing
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/test_model_parallel.py", line 434, in test_sharding_cw
    sharder_type=st.sampled_from(
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/hypothesis/core.py", line 1602, in wrapped_test
    raise the_error_hypothesis_found
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/test_model_parallel.py", line 491, in test_sharding_cw
    self._test_sharding(
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/test_model_parallel.py", line 198, in _test_sharding
    self._run_multi_process_test(
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/86458b9e59f64287/torchrec/distributed/tests/__test_model_parallel_nccl__/test_model_parallel_nccl#link-tree/torchrec/distributed/test_utils/multi_process.py", line 152, in _run_multi_process_test
    pool.map(runner, range(world_size))
  File "/usr/local/fbcode/platform010/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/fbcode/platform010/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
RuntimeError: injected error for testing
Falsifying example: test_sharding_cw(
    self=<torchrec.distributed.tests.test_model_parallel_nccl.ModelParallelTestNccl testMethod=test_sharding_cw>,
    sharder_type='embedding_bag_collection',
    kernel_type='fused',  # or any other generated value
    qcomms_config=None,  # or any other generated value
    apply_optimizer_in_backward_config=None,  # or any other generated value
    variable_batch_size=False,  # or any other generated value
    data_type=DataType.FP32,  # or any other generated value
    allow_zero_batch_size=False,  # or any other generated value
)
```

Differential Revision: D89102508