update python version in Generate documentation (#3483)
Summary:

# context
* torchrec github workflow starts to fail: [job](https://github.com/meta-pytorch/torchrec/actions/runs/18788899544/job/53619374395)
{F1982987922}

* error message
```
Run conda run -n build_binary pip install torch --index-url https://download.pytorch.org/whl/nightly/cpu
  conda run -n build_binary pip install torch --index-url https://download.pytorch.org/whl/nightly/cpu
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
ERROR conda.cli.main_run:execute(127): `conda run pip install torch --index-url https://download.pytorch.org/whl/nightly/cpu` failed. (See above for error)
Looking in indexes: https://download.pytorch.org/whl/nightly/cpu
```
* this is because PyTorch no longer support python 3.9 and this workflow still uses python 3.9
* update python version to 3.12 (the default version for ubuntu 20.04)
* workflow job succeeded: [job](https://github.com/meta-pytorch/torchrec/actions/runs/18790681229/job/53619962330)

Reviewed By: isururanawaka

Differential Revision: D85462203