fix github docs build issue updating to pytorch-sphinx-theme2 (#3670)
Summary:

# context
* https://fb.workplace.com/groups/4571909969591489/permalink/25746533765035802/
* instructions: [pytorch_sphinx_theme2_migration_guide](https://github.com/pytorch/pytorch_sphinx_theme/blob/pytorch_sphinx_theme2/pytorch_sphinx_theme2_migration_guide.md)
* github docs workflow started to [fail](https://github.com/meta-pytorch/torchrec/actions/runs/21075728300/job/60616964631)
```
Run conda run -n build_binary python -m pip install -r docs/requirements.txt
  Running command git clone --filter=blob:none --quiet https://github.com/pytorch/pytorch_sphinx_theme.git /home/runner/work/torchrec/torchrec/src/pytorch-sphinx-theme
  WARNING: Generating metadata for package pytorch_sphinx_theme produced metadata for project name pytorch-sphinx-theme2. Fix your #egg=pytorch_sphinx_theme fragments.
ERROR: Could not find a version that satisfies the requirement pytorch-sphinx-theme (unavailable) (from versions: 0.0.18, 0.0.19)
ERROR: No matching distribution found for pytorch-sphinx-theme (unavailable)

ERROR conda.cli.main_run:execute(127): `conda run python -m pip install -r docs/requirements.txt` failed. (See above for error)
Obtaining pytorch_sphinx_theme from git+https://github.com/pytorch/pytorch_sphinx_theme.git#egg=pytorch_sphinx_theme (from -r docs/requirements.txt (line 7))
  Cloning https://github.com/pytorch/pytorch_sphinx_theme.git to ./src/pytorch-sphinx-theme
  Resolved https://github.com/pytorch/pytorch_sphinx_theme.git to commit f532205d356b644f30b8bbd5c08699b250ca9dd0
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Discarding git+https://github.com/pytorch/pytorch_sphinx_theme.git#egg=pytorch_sphinx_theme: Requested pytorch-sphinx-theme2 from git+https://github.com/pytorch/pytorch_sphinx_theme.git#egg=pytorch_sphinx_theme (from -r docs/requirements.txt (line 7)) has inconsistent name: expected 'pytorch-sphinx-theme', but metadata has 'pytorch-sphinx-theme2'
Collecting sphinx==5.0.0 (from -r docs/requirements.txt (line 1))
  Downloading Sphinx-5.0.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: pyre-extensions in /usr/share/miniconda/envs/build_binary/lib/python3.12/site-packages (from -r docs/requirements.txt (line 2)) (0.0.32)
Collecting sphinx-design (from -r docs/requirements.txt (line 3))
  Downloading sphinx_design-0.6.1-py3-none-any.whl.metadata (5.5 kB)
Collecting sphinx_copybutton (from -r docs/requirements.txt (line 4))
  Downloading sphinx_copybutton-0.5.2-py3-none-any.whl.metadata (3.2 kB)
```
* update the pytorch-sphinx-theme2

Reviewed By: iamzainhuda

Differential Revision: D90876150